megasquirt:
  load: yes
  module: fixgw.plugins.megasquirt
  interface: socketcan
  channel: vcan0
  items:
    rpm: TACH1
    fuelflow: FUELF1
    clt: H2OT1
    map: MAP1
    tps: THR1
    #airtemp: intakeairtemp
    #afrtgt1: AFR Target for bank 1
    #AFR1: AFT for cyl1
    #egocor1: EGO Bank 1 correction
    #Ignition timing?

