system:
  load: yes
  module: fixgw.plugins.system
  time:
    enable: yes
    keys: # Database keys to write the time
      gmt_seconds: TIMEZS
      gmt_minutes: TIMEZM
      gmt_hours: TIMEZH
      gmt_string: TIMEZ
      local_seconds:
      local_minutes:
      local_hours:
      local_string: TIMEL
    gmt_format: "%H:%M:%S Z" # Zulu time format string
    local_format: "%H:%M:%S %Z" # Local time format string

