variables:
  e: 1  # Engines
  c: 6  # Cylinders
  a: 8  # Generic Analogs
  b: 16 # Generic Buttons
  g: 4  # Egt Buttons
  r: 4  # Encoders
  t: 3  # Fuel Tanks
  n: 5  # Nodes

entries:
- key: QVOTEn
  description: Quorum vote for node %n
  type: int
  tol: 1000
  initial: 0
  min: 0
  max: 500

- key: LEADER
  description: "The quorum plugin will set this false if those is not the leader, use it when making decisions to take actions"
  type: bool
  initial: true

- key: ANLGa
  description: Generic Analog %a
  type: float
  min: 0.0
  max: 1.0
  units: '%/100'
  initial: 0.0
  tol: 2000

- key: BTNb
  description: Generic Button %b
  type: bool
  tol: 0

- key: EGTBTNg
  description: EGT Button %b
  type: bool
  tol: 0

- key: ENCr
  description: Generic Encoder %r
  type: int
  min: -32768
  max: 32767
  units: Pulses
  initial: 0
  tol: 0

- key: IAS
  description: Indicated Airspeed
  type: float
  min: 0.0
  max: 1000.0
  units: knots
  initial: 0.0
  tol: 2000
  aux: [Min,Max,V1,V2,Vne,Vfe,Vmc,Va,Vno,Vs,Vs0,Vx,Vy]

- key: IASW
  description: Indicated Airspeed Warning
  type: int
  min: 0
  max: 5
  units: warninglevel
  initial: 0
  tol: 2000

- key: TAS
  description: True Airspeed
  type: float
  min: 0.0
  max: 2000.0
  units: knots
  initial: 0.0
  tol: 2000

- key: CAS
  description: True Airspeed
  type: float
  min: 0.0
  max: 2000.0
  units: knots
  initial: 0.0
  tol: 2000

- key: GS
  description: Ground Speed
  type: float
  min: 0.0
  max: 2000.0
  units: knots
  initial: 0.0
  tol: 2000

- key: ALT
  description: Indicated Altitude
  type: float
  min: -1000.0
  max: 60000.0
  units: ft
  initial: 0.0
  tol: 2000

- key: PALT
  description: Pressure Altitude
  type: float
  min: -1000.0
  max: 60000.0
  units: ft
  initial: 0.0
  tol: 2000

- key: TALT
  description: True Altitude
  type: float
  min: -1000.0
  max: 60000.0
  units: ft
  initial: 0.0
  tol: 2000

- key: DALT
  description: Density Altitude
  type: float
  min: -1000.0
  max: 60000.0
  units: ft
  initial: 0.0
  tol: 2000

- key: AGL
  description: Radar Altitude (Above Ground Level)
  type: float
  min: -1000.0
  max: 60000.0
  units: ft
  initial: 0.0
  tol: 2000

- key: BARO
  description: Altimeter Setting
  type: float
  min: 0.0
  max: 35.0
  units: inHg
  initial: 29.92
  tol: 2000

- key: AIRPRESS
  description: Air Pressure
  type: float
  min: 0.0
  max: 200000.0
  units: Pa
  initial: 101325.0
  tol: 2000

- key: DIFFAIRPRESS
  description: Differential Air Pressure
  type: float
  min: 0.0
  max: 200000.0
  units: Pa
  initial: 101325.0
  tol: 2000

- key: VS
  description: Vertical Speed
  type: float
  min: -30000.0
  max: 30000.0
  units: ft/min
  initial: 0.0
  tol: 2000
  aux: [Min,Max]

- key: HEAD
  description: Current Aircraft Magnetic Heading
  type: float
  min: 0.0
  max: 359.9
  units: deg
  initial: 0.0
  tol: 2000

- key: TRACK
  description: Current Aircraft Bearing
  type: float
  min: 0.0
  max: 359.9
  units: deg
  initial: 0.0
  tol: 2000

- key: TRACKM
  description: Current Aircraft Magnetic Bearing
  type: float
  min: 0.0
  max: 359.9
  units: deg
  initial: 0.0
  tol: 2000

- key: COURSE
  description: Selected Course
  type: float
  min: 0.0
  max: 359.9
  units: deg
  initial: 0.0
  tol: 2000

- key: CDI
  description: Course Deviation Indicator
  type: float
  min: -1.0
  max: 1.0
  initial: 0.0
  tol: 2000

- key: GSI
  description: Glideslope Indicator
  type: float
  min: -1.0
  max: 1.0
  initial: 0.0
  tol: 2000

- key: XTRACK
  description: Cross Track Error
  type: float
  min: 0.0
  max: 100.0
  units: nM
  initial: 0.0
  tol: 2000

- key: ROT
  description: Rate of Turn
  type: float
  min: -3000
  max: 3000
  units: Deg/sec
  initial: 0.0
  tol: 200

- key: OAT
  description: Outside Air Temperature
  type: float
  min: -100.0
  max: 100.0
  units: degC
  initial: 0.0
  tol: 2000
  aux: [Min,Max,lowWarn]

- key: CAT
  description: Cabin Air Temperature
  type: float
  min: -100.0
  max: 100.0
  units: degC
  initial: 0.0
  tol: 2000
  aux: [Min,Max,lowWarn,highWarn,lowAlarm,highAlarm]

- key: OATW
  description: Outside Air Temperature Warning
  type: int
  min: 0
  max: 5
  units: warninglevel
  initial: 0
  tol: 2000

- key: ROLL
  description: Roll Angle
  type: float
  min: -180.0
  max: 180.0
  units: deg
  initial: 0.0
  tol: 300

- key: PITCH
  description: Pitch Angle
  type: float
  min: -90.0
  max: 90.0
  units: deg
  initial: 0.0
  tol: 300

- key: ORISYSW
  description: Orientation System Warning
  type: int
  min: 0
  max: 5
  units: warninglevel
  initial: 0
  tol: 2000

- key: GYROW
  description: Gyroscope sensor Warning
  type: int
  min: 0
  max: 5
  units: warninglevel
  initial: 0
  tol: 2000

- key: ACCELW
  description: Acceleration sensor Warning
  type: int
  min: 0
  max: 5
  units: warninglevel
  initial: 0
  tol: 2000

- key: MAGW
  description: Magnetic sensor Warning
  type: int
  min: 0
  max: 5
  units: warninglevel
  initial: 0
  tol: 2000

- key: PITCHSET
  description: Pitch angle setting
  type: float
  min: -180.0
  max: 180.0
  units: deg
  initial: 0.0
  tol: 200

- key: YAW
  description: Yaw Angle
  type: float
  min: -180.0
  max: 180.0
  units: deg
  initial: 0.0
  tol: 200

- key: AOA
  description: Angle of attack
  type: float
  min: -180.0
  max: 180.0
  units: deg
  initial: 0.0
  tol: 200
  aux: [Min, Max, 0g, Warn, Stall]

- key: CTLPTCH
  description: Pitch Control
  type: float
  min: -1.0
  max: 1.0
  units: '%/100'
  initial: 0.0
  tol: 200

- key: CTLROLL
  description: Roll Control
  type: float
  min: -1.0
  max: 1.0
  units: '%/100'
  initial: 0.0
  tol: 200

- key: CTLYAW
  description: Yaw Control (Rudder)
  type: float
  min: -1.0
  max: 1.0
  units: '%/100'
  initial: 0.0
  tol: 200

- key: CTLCOLL
  description: Collective Control
  type: float
  min: -1.0
  max: 1.0
  units: '%/100'
  initial: 0.0
  tol: 200

- key: CTLATP
  description: AntiTorque Pedal Ctrl
  type: float
  min: -1.0
  max: 1.0
  units: '%/100'
  initial: 0.0
  tol: 200

- key: CTLFLAP
  description: Flap Control
  type: float
  min: -1.0
  max: 1.0
  units: '%/100'
  initial: 0.0
  tol: 200

- key: CTLLBRK
  description: Left Brake Control
  type: float
  min: 0.0
  max: 1.0
  units: '%/100'
  initial: 0.0
  tol: 200

- key: CTLRBRK
  description: Right Brake Control
  type: float
  min: 0.0
  max: 1.0
  units: '%/100'
  initial: 0.0
  tol: 1000

- key: ANORM
  description: Normal Acceleration
  type: float
  min: -30.0
  max: 30.0
  units: g
  initial: 0.0
  tol: 200

- key: ALAT
  description: Lateral Acceleration
  type: float
  min: -30.0
  max: 30.0
  units: g
  initial: 0.0
  tol: 200

- key: ALONG
  description: Longitudinal Acceleration
  type: float
  min: -30.0
  max: 30.0
  units: g
  initial: 0.0
  tol: 200

- key: THRe
  description: Throttle Control Engine %e
  type: float
  min: 0.0
  max: 1.0
  units: '%/100'
  initial: 0.0
  tol: 1000

- key: MIXe
  description: Mixture Control Engine %e
  type: float
  min: 0.0
  max: 1.0
  units: '%/100'
  initial: 0.0
  tol: 1000

- key: OILPe
  description: Oil Pressure Engine %e
  type: float
  min: 0.0
  max: 200.0
  units: psi
  initial: 0.0
  tol: 2000
  aux: [Min,Max,lowWarn,highWarn,lowAlarm,highAlarm]

- key: OILTe
  description: Oil Temperature Engine %e
  type: float
  min: 0.0
  max: 150.0
  units: degC
  initial: 0.0
  tol: 2000
  aux: [Min,Max,lowWarn,highWarn,lowAlarm,highAlarm]

- key: H2OTe
  description: Coolant Temperature Engine %e
  type: float
  min: 0.0
  max: 200.0
  units: degC
  initial: 0.0
  tol: 2000
  aux: [Min,Max,lowWarn,highWarn,lowAlarm,highAlarm]

- key: FUELPe
  description: Fuel Pressure Engine %e
  type: float
  min: 0.0
  max: 200.0
  units: psi
  initial: 0.0
  tol: 2000
  aux: [Min,Max,lowWarn,highWarn,lowAlarm,highAlarm]

- key: FUELFe
  description: Fuel Flow Engine %e
  type: float
  min: 0.0
  max: 100.0
  units: gal/hr
  initial: 0.0
  tol: 2000
  aux: [Min,Max]

- key: MAPe
  description: Manifold Pressure Engine %e
  type: float
  min: 0.0
  max: 60.0
  units: inHg
  initial: 0.0
  tol: 2000
  aux: [Min,Max,highWarn,highAlarm]

- key: VOLT
  description: System Voltage
  type: float
  min: 0.0
  max: 18.0
  units: volt
  initial: 0.0
  tol: 2000
  aux: [Min,Max,lowWarn,highWarn,lowAlarm,highAlarm]

- key: CURRNT
  description: Bus Current
  type: float
  min: 0.0
  max: 60.0
  units: amps
  initial: 0.0
  tol: 2000
  aux: [Min,Max,lowWarn,highWarn,lowAlarm,highAlarm]

- key: EGTec
  description: Exhaust Gas Temp Engine %e, Cylinder %c
  type: float
  min: 0.0
  max: 1000.0
  units: degC
  initial: 0.0
  tol: 2000
  aux: [Min,Max,lowWarn,highWarn,lowAlarm,highAlarm]

- key: EGTAVGe
  description: Average Exhaust Gas Temp Engine %e
  type: float
  min: 0.0
  max: 1000.0
  units: degC
  initial: 0.0
  tol: 0
  aux: [Min,Max]

- key: EGTSPANe
  description: Exhaust Gas Temp Span Engine %e
  type: float
  min: 0.0
  max: 1000.0
  units: degC
  initial: 0.0
  tol: 0
  aux: [Min,Max]

- key: EGTMAXe
  description: Maximum Exhaust Gas Temp Engine %e
  type: float
  min: 0.0
  max: 1000.0
  units: degC
  initial: 0.0
  aux: [Min,Max,lowWarn,highWarn,lowAlarm,highAlarm]

- key: CHTec
  description: Cylinder Head Temp Engine %e, Cylinder %c
  type: float
  min: 0.0
  max: 1000.0
  units: degC
  initial: 0.0
  tol: 2000
  aux: [Min,Max,lowWarn,highWarn,lowAlarm,highAlarm]

- key: CHTMAXe
  description: Maximum Cylinder Head Temp Engine %e
  type: float
  min: 0.0
  max: 1000.0
  units: degC
  initial: 0.0
  aux: [Min,Max,lowWarn,highWarn,lowAlarm,highAlarm]

- key: FUELQt
  description: Fuel Quantity Tank %t
  type: float
  min: 0.0
  max: 200.0
  units: gal
  initial: 0.0
  tol: 2000
  aux: [Min,Max,lowWarn,lowAlarm]

- key: FUELQT
  description: Total Fuel Quantity
  type: float
  min: 0.0
  max: 200.0
  units: gal
  initial: 0.0
  tol: 2000
  aux: [Min,Max,lowWarn,lowAlarm]

- key: TACHe
  description: Engine RPM Engine %e
  type: int
  min: 0
  max: 10000
  units: RPM
  initial: 0
  tol: 2000
  aux: [Min,Max,lowWarn,highWarn,lowAlarm,highAlarm]

- key: PROPe
  description: Propeller RPM Engine %e
  type: int
  min: 0
  max: 10000
  units: RPM
  initial: 0
  tol: 2000
  aux: [Min,Max,lowWarn,highWarn,lowAlarm,highAlarm]

- key: LAT
  description: Latitude
  type: float
  min: -90.0
  max: 90.0
  units: deg
  initial: 0.0
  tol: 2000

- key: LONG
  description: Longitude
  type: float
  min: -180.0
  max: 180.0
  units: deg
  initial: 0.0
  tol: 2000

- key: TIMEZ
  description: Zulu Time String
  type: str
  tol: 2000

- key: TIMEZH
  description: Zulu Time Hour
  type: int
  min: 0
  max: 23
  initial: 0
  tol: 2000

- key: TIMEZM
  description: Zulu Time Minute
  type: int
  min: 0
  max: 59
  initial: 0
  tol: 2000

- key: TIMEZS
  description: Zulu Time Second
  type: int
  min: 0
  max: 59
  initial: 0
  tol: 2000

- key: TIMEL
  description: Local Time String
  type: str
  tol: 0

- key: TZONE
  description: Time Zone
  type: float
  min: -12.0
  max: 12.0
  initial: 0.0

- key: FTIME
  description: Flight Time
  type: float
  min: 0.0
  max: 1000.0
  initial: 0.0

- key: DIM
  description: Panel Dimmer Level
  type: int
  min: 0
  max: 100
  initial: 100

- key: HOBBS1
  description: Total Engine Time %e
  type: float
  min: 0.0
  max: 100000.0
  units: Hours
  initial: 0.0

- key: ACID
  description: Aircraft Identification
  type: str
  tol: 0

# Used by mavlink plugin:
- key: TRIMP
  description: Pitch Trim
  type: int
  min: -1000
  max: 1000
  initial: 0
- key: TRIMR
  description: Roll Trim
  type: int
  min: -1000
  max: 1000
  initial: 0
- key: TRIMY
  description: Yaw Trim
  type: int
  min: -1000
  max: 1000
  initial: 0
- key: BTNTRIMUP
  description: Trim up button
  type: bool
  initial: false
- key: BTNTRIMDN
  description: Trim down button
  type: bool
  initial: false
- key: BTNTRIMCT
  description: Trim center button
  type: bool
  initial: false
- key: BTNTRIMYL
  description: Yaw Left button
  type: bool
  initial: false
- key: BTNTRIMYR
  description: Yaw Right button
  type: bool
  initial: false
- key: BTNTRIMYC
  description: Yaw center button
  type: bool
  initial: false
- key: BTNTRIMRL
  description: Roll Left button
  type: bool
  initial: false
- key: BTNTRIMRR
  description: Roll Right button
  type: bool
  initial: false
- key: BTNTRIMRC
  description: Roll center button
  type: bool
  initial: false

- key: BTNAP
  description: AP button state
  type: bool
  initial: false
- key: BTNHH
  description: AP heading hold button state
  type: bool
  initial: false
- key: BTNFP
  description: AP flight plan button state
  type: bool
  initial: false
- key: APSTAT
  description: Status of auto pilot, Avaliable or not
  type: str
  tol: 10000
  initial: INIT
- key: APMODE
  description: Mode of auto pilot, Heading Hold (CRUISE), Trim (Manual), AUTO fly to waypoint
  type: str
  initial: TRIM
  tol: 10000
- key: APMSG
  description: Auto Pilot Message for pilot
  type: str
  initial: ""
- key: APWPV
  description: Does AP have a valid waypoint to navigate to
  type: bool
  initial: False
- key: APREQ
  description: Mode of auto pilot that is requested
  type: str
  initial: "INIT"
- key: APADJ
  description: Adjust heading/altitude of auto pilot using trim controls
  type: bool
  initial: False

# Used by ifly and mavlink
- key: WPLAT
  description: Waypoint Latitude
  type: float
  initial: 0.0
  min: -90
  max: 90
  tol: 50000
- key: WPLON
  description: Waypoint Longitude
  type: float
  initial: 0.0
  min: -90
  max: 90
  tol: 50000
- key: WPNAME
  description: Waypoint Name
  type: str
  tol: 50000
  initial: ""
- key: WPHEAD
  description: Heading to waypoint
  type: str
  tol: 50000
  initial: ""

